import {
  type BotAccess,
  CATEGORY_LABELS,
  type CategoryScore,
  type Finding,
  RULE_CATEGORIES,
  type ScanReport,
  type Severity,
  type SiteReport,
} from '../core/types.js';

const SEV_EMOJI: Record<Severity, string> = { error: '❌', warn: '⚠️', info: 'ℹ️' };
const SEV_RANK: Record<Severity, number> = { error: 0, warn: 1, info: 2 };

/** Escape table-cell text: pipes must not break the markdown table. */
function cell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();
}

function plural(n: number, singular: string, pluralWord = `${singular}s`): string {
  return `${n} ${n === 1 ? singular : pluralWord}`;
}

function issueText(cat: CategoryScore): string {
  const total = cat.errors + cat.warnings + cat.infos;
  if (cat.rulesRun.length === 0) {
    return '—';
  }
  if (total === 0) {
    return '✅ clean';
  }
  const parts: string[] = [];
  if (cat.errors > 0) {
    parts.push(plural(cat.errors, 'error'));
  }
  if (cat.warnings > 0) {
    parts.push(plural(cat.warnings, 'warning'));
  }
  if (cat.infos > 0) {
    parts.push(plural(cat.infos, 'hint'));
  }
  return parts.join(' · ');
}

function categoryRows(categories: ScanReport['categories']): string[] {
  const lines = ['| Category | Score | Issues |', '| --- | ---: | --- |'];
  for (const cat of RULE_CATEGORIES) {
    const cs = categories[cat];
    const score = cs.rulesRun.length === 0 ? '—' : String(cs.score);
    lines.push(`| ${CATEGORY_LABELS[cat]} | ${score} | ${issueText(cs)} |`);
  }
  return lines;
}

function findingRows(findings: Finding[]): string[] {
  const sorted = [...findings].sort((a, b) => SEV_RANK[a.severity] - SEV_RANK[b.severity]);
  const lines = ['| Severity | Rule | Finding | Fix |', '| --- | --- | --- | --- |'];
  for (const f of sorted) {
    lines.push(
      `| ${SEV_EMOJI[f.severity]} ${f.severity} | \`${f.ruleId}\` | ${cell(f.message)} | ${cell(f.fix ?? '—')} |`,
    );
  }
  return lines;
}

function uniqueFixes(findings: Finding[]): string[] {
  const seen = new Set<string>();
  const fixes: string[] = [];
  for (const f of findings) {
    if (f.fix && !seen.has(f.fix)) {
      seen.add(f.fix);
      fixes.push(f.fix);
    }
  }
  return fixes;
}

function improvementsBlock(findings: Finding[]): string[] {
  const fixes = uniqueFixes(findings);
  if (fixes.length === 0) {
    return [];
  }
  return [
    '<details><summary>How to improve</summary>',
    '',
    ...fixes.map((fix) => `- ${cell(fix)}`),
    '',
    '</details>',
  ];
}

function botSummary(bots: BotAccess[]): string | null {
  if (bots.length === 0) {
    return null;
  }
  const allowed = bots.filter((b) => b.allowed === true).length;
  const blocked = bots.filter((b) => b.allowed === false).length;
  const unknown = bots.length - allowed - blocked;
  const parts = [`${allowed}/${bots.length} allowed`];
  if (blocked > 0) {
    parts.push(`${blocked} blocked`);
  }
  if (unknown > 0) {
    parts.push(`${unknown} unknown`);
  }
  return `**AI crawler access:** ${parts.join(' · ')}`;
}

function dateLabel(iso: string): string {
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? iso : d.toISOString().slice(0, 10);
}

/** PR-comment-ready markdown for a single-page audit. */
export function renderMarkdown(report: ScanReport): string {
  const L: string[] = [];
  L.push(`## 🛰️ geolint — ${report.score}/100 (${report.grade})`);
  L.push('');
  const urlBits = [`**${report.url}**`];
  if (report.finalUrl !== report.url) {
    urlBits.push(`→ ${report.finalUrl}`);
  }
  urlBits.push(`scanned ${dateLabel(report.scannedAt)}`);
  urlBits.push(`${report.durationMs}ms`);
  L.push(urlBits.join(' · '));
  const bots = botSummary(report.bots);
  if (bots) {
    L.push('');
    L.push(bots);
  }
  L.push('');
  L.push(...categoryRows(report.categories));
  if (report.findings.length > 0) {
    L.push('');
    L.push('### Findings');
    L.push('');
    L.push(...findingRows(report.findings));
  }
  const improvements = improvementsBlock(report.findings);
  if (improvements.length > 0) {
    L.push('');
    L.push(...improvements);
  }
  L.push('');
  L.push('---');
  L.push('*Generated by [geolint](https://github.com/iliasaberkane/geolint)*');
  return `${L.join('\n')}\n`;
}

function pagePath(url: string): string {
  try {
    const u = new URL(url);
    return `${u.pathname}${u.search}`;
  } catch {
    return url;
  }
}

function topIssue(page: ScanReport): string {
  let errors = 0;
  let warnings = 0;
  let infos = 0;
  for (const f of page.findings) {
    if (f.severity === 'error') {
      errors += 1;
    } else if (f.severity === 'warn') {
      warnings += 1;
    } else {
      infos += 1;
    }
  }
  if (errors > 0) {
    return `❌ ${plural(errors, 'error')}`;
  }
  if (warnings > 0) {
    return `⚠️ ${plural(warnings, 'warning')}`;
  }
  if (infos > 0) {
    return `ℹ️ ${plural(infos, 'hint')}`;
  }
  return '✅ clean';
}

/** PR-comment-ready markdown for a multi-page (crawl) audit. */
export function renderSiteMarkdown(report: SiteReport): string {
  const L: string[] = [];
  L.push(`## 🛰️ geolint — ${report.score}/100 (${report.grade})`);
  L.push('');
  L.push(
    `**${report.url}** · scanned ${dateLabel(report.scannedAt)} · ${report.durationMs}ms · ${plural(report.stats.pagesScanned, 'page')} (${report.stats.pagesFailed} failed)`,
  );
  L.push('');
  if (report.pages.length > 0) {
    const sorted = [...report.pages].sort((a, b) => a.score - b.score);
    L.push('| Page | Score | Grade | Top issue |');
    L.push('| --- | ---: | :---: | --- |');
    for (const page of sorted) {
      L.push(
        `| ${cell(pagePath(page.finalUrl || page.url))} | ${page.score} | ${page.grade} | ${topIssue(page)} |`,
      );
    }
    L.push('');
  }
  L.push(...categoryRows(report.categories));
  if (report.findings.length > 0) {
    L.push('');
    L.push('### Findings');
    L.push('');
    const deduped = [
      ...new Map(report.findings.map((f) => [`${f.ruleId}${f.message}`, f])).values(),
    ];
    L.push(...findingRows(deduped));
  }
  const improvements = improvementsBlock(report.findings);
  if (improvements.length > 0) {
    L.push('');
    L.push(...improvements);
  }
  L.push('');
  L.push('---');
  L.push('*Generated by [geolint](https://github.com/iliasaberkane/geolint)*');
  return `${L.join('\n')}\n`;
}
