/**
 * Generate docs/rules.md from the rule registry.
 * Usage: npx tsx scripts/gen-rules-docs.ts
 */
import { writeFileSync } from 'node:fs';
import { CATEGORY_LABELS, RULE_CATEGORIES, type Rule } from '../src/core/types.js';
import { allRules } from '../src/rules/index.js';

const SEVERITY_BADGE: Record<Rule['severity'], string> = {
  error: '🔴 error',
  warn: '🟡 warn',
  info: '🔵 info',
};

/** Anchor used in SARIF helpUri and cross-links. Must match the emitted <a id>. */
export function ruleAnchor(id: string): string {
  return `rule-${id.replace('/', '-')}`;
}

const lines: string[] = [
  '# geolint rules',
  '',
  `geolint ships **${allRules.length} rules** across ${RULE_CATEGORIES.length} categories.`,
  'Each rule documents what it checks, why it matters for AI search visibility, and how to fix violations.',
  '',
];

for (const cat of RULE_CATEGORIES) {
  const rules = allRules.filter((r) => r.category === cat);
  if (rules.length === 0) {
    continue;
  }
  lines.push(`## ${CATEGORY_LABELS[cat]}`, '');
  for (const rule of rules) {
    lines.push(
      `<a id="${ruleAnchor(rule.id)}"></a>`,
      `### \`${rule.id}\` — ${rule.title}`,
      '',
      `**Severity:** ${SEVERITY_BADGE[rule.severity]}`,
      '',
      rule.description,
      '',
    );
  }
}

lines.push(
  '---',
  '',
  '_This file is generated by `scripts/gen-rules-docs.ts`. Do not edit by hand._',
  '',
);

writeFileSync(new URL('../docs/rules.md', import.meta.url), lines.join('\n'));
console.log(`docs/rules.md written (${allRules.length} rules)`);
